import React from 'react';
import Head from 'next/head';
import { ElementProps } from '../interfaces';

const Layout = ({ children }: ElementProps): JSX.Element => {
  return (
    <>
      <Head>
        <title>Authentication app</title>
        <meta name="description" content="Generated by laszlokovacs" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{children}</main>
    </>
  );
};

export default Layout;
